name: Rotate Product Configuration

on:
  workflow_dispatch:
    inputs: 
      repo:
        description: 'Repo to rotate (owner/repo)'
        required: true
        type: string
        # Accessible at the caller as ${{github.repository}}
      event_type:
        description: 'Event type (branch|tag)'
        required: true
        type: string
        # Accessible at the caller as ${{github.ref_type}}
      event_name:
        description: 'Actual name of the branch or tag '
        required: true
        type: string
        # Accessible at the caller as ${{github.ref_name}}
      sha:
        description: 'SHA of the commit to lock in the manifest'
        required: true
        type: string
        # Accessible at the caller as ${{github.sha}}

jobs:
  rotate:
    name: Rotate (lock manifest)
    permissions:
      actions: write
    
    secrets:
      token: ${{ secrets.ROTATOR_COMMIT_TOKEN }}
    
    uses: thetechcollective/gh-rotator/.github/workflows/rotator.yml@experimental
    
    with:
      repo: ${{ inputs.repo }}
      event_type: ${{ inputs.event_type }}
      event_name: ${{ inputs.event_name }}
      sha: ${{ inputs.sha }}
      user_name: gh-rotator
      user_email: gh-rotator@thetechcollective.dev
      rotator-pin: experimental
